# Generated by Django 3.0.9 on 2020-08-04 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('playername', models.CharField(max_length=150)),
                ('points', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='nba_app.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='nba_app.Team')),
            ],
        ),
    ]
