# Generated by Django 3.0.8 on 2020-07-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='player_id',
            new_name='player',
        ),
    ]
