# Generated by Django 3.0.9 on 2020-08-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0002_player_games_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='nba_app.Team'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
