# Generated by Django 3.0.8 on 2020-07-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0002_auto_20200723_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nba_app.Player')),
                ('score', models.IntegerField(default=0)),
                ('rebound', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='teams',
            name='id',
        ),
        migrations.AddField(
            model_name='teams',
            name='team',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
