# Generated by Django 3.0.8 on 2020-07-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0008_auto_20200726_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nba_app.Player')),
                ('score', models.IntegerField(default=0)),
                ('rebound', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='playerName',
            new_name='playername',
        ),
        migrations.CreateModel(
            name='OnTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_app.Player')),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='nba_app.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='nba_app.Team')),
            ],
        ),
    ]
