# Generated by Django 3.0.8 on 2020-07-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0009_auto_20200726_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='playername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_app.Name'),
        ),
    ]
