# Generated by Django 3.0.8 on 2020-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0010_auto_20200726_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playername',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
